version: "3.8"
services:
  todo_mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=dbpass
      - MYSQL_DATABASE=todo_task_app
    volumes:
      - todo_task_app:/var/lib/mysql

volumes:
  todo_task_app:
    driver: local